<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Ingredient;
use AppBundle\Entity\Quantite;

/**
 * IngredientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IngredientRepository extends \Doctrine\ORM\EntityRepository
{
//    public function findIngredient(){
//
//        return $this->createQueryBuilder('u')
//            ->select('u., u.fk_ingredient')
//            ->from(Ingredient::class, 'u')
//            ->where('u.fk_recette = :fk_recette');


}
