<?php

namespace AppBundle\Repository;

/**
 * QuantiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuantiteRepository extends \Doctrine\ORM\EntityRepository
{
}
