<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Ingredient;
use AppBundle\Entity\Recette;
use Doctrine\ORM\Query\Expr\Join;

/**
 * QuantiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuantiteRepository extends \Doctrine\ORM\EntityRepository
{
    public function findQuantiteByIngredient($id)
    {
        return $this->createQueryBuilder('q')
            ->select('q.id', 'q.quantite', 'i.nom', 'i.nutriScore', 'i.mesure', 'i.urlPhoto', 'i.allergene')
            ->where('q.id =' .$id)
            ->innerJoin('q.fkRecette', 'qr', \Doctrine\ORM\Query\Expr\Join::WITH, 'q.fkRecette = qr.id' )
            ->innerJoin('q.fkIngredient', 'qi', \Doctrine\ORM\Query\Expr\Join::WITH, 'q.fkIngredient = qi.id' )
            ->getQuery()
            ->getResult();
    }


//    public function findQuantiteByIngredient(Recette $recette, Ingredient $ingredient){
//
//
//         return $this->createQueryBuilder('q')
//                    ->select('q.quantite, q.fkIngredient', 'q.fkRecette')
//                    ->where('q.fkRecette = :fkRecette')
//                    ->andWhere('q.fkIngredient = :fkIngredient')
//                    ->setParameter('fkRecette', $recette)
//                   ->setParameter('fkIngredient', $ingredient);
//    }

}

