<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Ingredient;
use AppBundle\Entity\Recette;

/**
 * QuantiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuantiteRepository extends \Doctrine\ORM\EntityRepository
{
    public function findQuantite(Recette $recette, Ingredient $ingredient){


         return $this->createQueryBuilder('q')
                    ->select('q.quantite, q.fk_ingredient')
                    ->where('q.fk_recette = :fk_recette')
                    ->andWhere('q.fk_ingredient = :fk_ingredient')
                    ->setParameter('fk_recette', $recette)
                    ->setParameter('fk_ingredient', $ingredient);

    }
}
