<?php

namespace AppBundle\Repository;

/**
 * RecetteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecetteRepository extends \Doctrine\ORM\EntityRepository
{
//    public function showRecipe()
//    {
//        return $this->getEntityManager()
//            ->createQuery(
//                'SELECT nom FROM AppBundle:Recette nom ORDER BY ASC'
//            )
//            ->getResult();
//    }

}
